CREATE DATABASE[Audit]
GO
USE[Audit]
GO
CREATE TABLE[Categories](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[Bet] INT NOT NULL
);
GO
CREATE TABLE[Employee](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[SurName] NVARCHAR(50) NOT NULL,
[MidleName] NVARCHAR(50) NOT NULL,
[NumberPass] INT NOT NULL,
[Birthday] DATE NOT NULL,
[PhoneNumber] INT,
[CategoriesID] INT FOREIGN KEY REFERENCES [Categories](ID) NOT NULL
);
GO
CREATE TABLE[Work](
[ID] INT PRIMARY KEY IDENTITY,
[NameCompany] NVARCHAR(50) NOT NULL,
[Date] DATE NOT NULL,
[WorkTime] INT NOT NULL
);
CREATE TABLE[Report](
[ID] INT PRIMARY KEY IDENTITY,
[EmployeeID] INT FOREIGN KEY REFERENCES [Employee](ID) NOT NULL,
[WorkID] INT FOREIGN KEY REFERENCES [Work](ID) NOT NULL
);
